### ISSUE TITLE
summary function on meta object very(!) slow.

### ISSUE THREAD

**Issue by jmetzel** [mikewlcheung/metasem#2]
Dear Mike, 
I am currently using your package to conduct multivariate metaanalyses of individual profile data. The OpenMX models converge pretty fast (~5-10 seconds) but when i try to call the summary of the class meta object it takes several minutes before the output is printed. This issue must be inherent to your summary.meta() function, since the corresponding fitted openmx output (via summary(metaobject$mx.fit) is produced really fast (~1-2 seconds). 

Sincerely
Julian

**Comment by mikewlcheung** [comment]
Dear Julian,

it could be due to the extra calculations in either the I2 or R2. Would you mind posting or emailing me the data for testing? Thanks.

Best,
Mike

**Comment by mikewlcheung** [comment]
Dear Julian,

Thanks for sending the data to me. The bottleneck is the calculation of the homogeneity test (please see the following comparisons). You may disable it by using homoStat=FALSE in the summary().

Best,
Mike

> system.time(summary(xx))
   user  system elapsed 
 59.918  40.914   4.956 
> system.time(summary(xx, homoStat=FALSE))
   user  system elapsed 
  0.011   0.000   0.011 
> system.time(summary(xx$mx.fit))
   user  system elapsed 
  0.008   0.000   0.008
