### ISSUE TITLE
Different behaviour when loading or attaching

### ISSUE THREAD

**Issue by ghost** [mikewlcheung/metasem#3]
I noticed a different behaviour of metaSEM depending on whether it is loaded or attached. At first, I thought this issue was due to OpenMx, but as dicussed [here](https://github.com/OpenMx/OpenMx/issues/98), it is not due to OpenMx, but very likely to the missing .onLoad() function in metaSEM (so the default options are not set when just loading, but not attaching the package). Did you leave this function .onLoad() out intentionally or is this a bug?

**Comment by mikewlcheung** [comment]
Thanks for catching that. I have just added .onLoad().

**Comment by ghost** [comment]
Thanks, it's fixed now. However, I now get all package startup messages doubled when attaching the package metaSEM. This is probably due to the copies of the startup messages in .onLoad() that are also in .onAttach(). According to [this book by Hadley Wickham](http://r-pkgs.had.co.nz/namespace.html), attaching a package also loads it.

**Comment by mikewlcheung** [comment]
It is fixed now. Thanks again!
