### ISSUE TITLE
Computation of the standard error in metaSEM

### ISSUE THREAD

**Issue by RobbievanAert** [mikewlcheung/metasem#7]
Hi Mike,

I am wondering how the standard errors of the estimated fixed effects are computed in the metaSEM package. I worked through the examples in your book and realized that the standard error in the output deviates slightly from when the standard error is computed using the formulas in the book.

Here is an example based on the Jaramillo data set:

`library(metaSEM)`
`### Fit random-effects model using the code on page 109 of Cheung (2015)`
`res <- summary( meta(y=r, v=r_v, data=Jaramillo05) )`
`res$coefficients["Intercept1","Std.Error"] # Standard error in output`
[1] 0.01933031

`### Standard error computed by hand`
`wi <- 1/(Jaramillo05$r_v+res$coefficients["Tau2_1_1","Estimate"])`
`sqrt(1/sum(wi)) # Square root of equation (4.26) in Cheung (2015)`
[1] 0.01932767

I agree that the difference is small, but I would like to know what is causing the difference and it might be larger in other cases. 

Thank you in advance for your response!

Best,
Robbie

**Comment by mikewlcheung** [comment]
Hi Robbie,

The metaSEM package formulates a meta-analytic model as a structural equation model (SEM) and uses the OpenMx package (https://openmx.ssri.psu.edu/) as the backend for all the computations. OpenMx is a standard SEM package that uses maximum likelihood estimation to estimate the parameters and their standard errors. Therefore, I speculate that the slight difference is due to numerical issues.

Are you working on specific models that have a large discrepancy?

Best,
Mike

**Comment by RobbievanAert** [comment]
Hi Mike,

Thank you for your reply. This is also what I expected already. OpenMx probably computes the standard error using the observed Fisher information. 

I was just working through the examples in the book and realized that the test statistics were somewhat different. This was caused by the differences in estimated standard errors.

I believe that the differences will be minor in the vast majority of applications. You can, however, come up with some pathological cases where the difference is substantial. For example,

`vi <- c(0.03, 0.4, 0.45)`
`yi <- c(0.2, -0.6, -1.2)`
 
`res <- summary( meta(y=yi, v=vi) )`
`res$coefficients["Intercept1","Std.Error"] # Standard error in output`
`[1] 0.4876507`

`wi <- 1/(vi+res$coefficients["Tau2_1_1","Estimate"])`
`sqrt(1/sum(wi)) # Square root of equation (4.26) in Cheung (2015)`
`[1] 0.3139785`

`res$coefficients["Intercept1","Std.Error"]/sqrt(1/sum(wi)) # Ratio largest vs. smallest standard error`
`[1] 1.553134`

Best,
Robbie

**Comment by mikewlcheung** [comment]
Hi Robbie,

Yes, I believe that OpenMx uses the observed Fisher information to calculate the standard errors.

It could be related to the large discrepancy on vi. When I change 0.03 to 0.3, the difference becomes much smaller.

Best,
Mike

**Comment by RobbievanAert** [comment]
Hi Mike,

Yes, it is indeed related to the large differences in vi. 

Thanks for the explanation! I now know what is causing the discrepancy. I will close this issue.

Best,
Robbie
