### ISSUE TITLE
Bug in the "if (!is.pd(x.new)) stop("x is not positive definite!\n")" line of the code

### ISSUE THREAD

**Issue by Mraknight3** [mikewlcheung/metasem#8]
While running the metaSEM code, I get an error that reads:

Error in if (!is.pd(x.new)) stop("x is not positive definite!\n") : 
  missing value where TRUE/FALSE needed

**Comment by mikewlcheung** [comment]
Could you please provide a reproducible example?

**Comment by mikewlcheung** [comment]
I have closed the issue for now. Please reopen it if you have a reproducible example.
