### ISSUE TITLE
Argument "byrow" in function "vec2symMat"

### ISSUE THREAD

**Issue by yiorfun** [mikewlcheung/metasem#9]
Hello Mike, 

I was wondering if I use the function "vec2symMat" incorrectly to convert a p * (p + 1) dimensional vector to a p by p symmetric matrix by row. 

For example, p = 3, the vector is c(1, 2, 3, 4, 5, 6), the corresponding symmetric matrix (by row) should be 

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    4    5
[3,]    3    5    6

However, it seems the argument "byrow" should be "FALSE" (rather than "TRUE", please see below) using the function "vec2symMat". But this design is not consistent with that of the argument "byrow" in the build-in function matrix(). Could you please double-check this? Thanks so much. 

The code is as below. 

> vec2symMat(seq(6), diag = TRUE, byrow = TRUE)
     [,1] [,2] [,3]
[1,]    1    2    4
[2,]    2    3    5
[3,]    4    5    6

> vec2symMat(seq(6), diag = TRUE, byrow = FALSE)
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    4    5
[3,]    3    5    6

**Comment by mikewlcheung** [comment]
Thanks for raising this issue.

According to the manual, it converts a vector into a symmetric matrix by filling up the elements into the lower triangle of the matrix. Thus, the "byrow" argument refers to filling elements in the lower triangle matrix, not the upper triangle matrix.
